language: go
go:
- 1.10.x
sudo: false
dist: trusty
addons:
  apt:
    packages:
      - realpath
env:
  global:
  - PATH=$PATH:$GOPATH/bin
before_install:
- set -e
- go get github.com/mattn/goveralls
script:
- go test -v -covermode=count -coverprofile=/tmp/coverage.out ./...
- $HOME/gopath/bin/goveralls -coverprofile=/tmp/coverage.out -race -service=travis-ci -package github.com/ksonnet/ksonnet/...
- go vet ./...
after_script: set +e
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+\\.\\d+.*$/"
notifications:
  email:
    on_success: never
